### ISSUE TITLE
Артур Пайкин

### ISSUE THREAD

**Issue by arturi** [roman01la/js-mentor#2]
Веб-разработчик. Готов помочь с JavaScript, Node, HTML, CSS.

http://twitter.com/arturi
http://arturpaikin.com
Связаться можно по почте: artur@arturpaikin.com

**Comment by zorro76** [comment]
Написал Вам на почту по поводу проблемы с отображением js элемента (slick slider) в аккордеоне Bootstrap

**Comment by arturi** [comment]
Горшочек не вари!
